name: ovpn3-connector
description: 
  Setup vpn using a self-contained .ovpn file on both Windows and Linux
inputs:
  ovpn-config:
    description: Complete self-contained .ovpn file
    required: true
  vpn-user:
    description: Username for the VPN
    required: false
  vpn-pass:
    description: Password for the VPN
    required: false
runs:
  using: composite
  steps:
    # Steps for Linux runners
    - name: Write VPN Files (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ovpn-config }}" > .github/vpn.ovpn
        ls -al .github/vpn.ovpn
    - name: Install openvpn3 (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install openvpn
    - name: VPN Connect (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        { printf "${{ inputs.vpn-user }}\n${{ inputs.vpn-pass }}\n" ; } | sudo openvpn --config .github/vpn.ovpn --daemon

    # Steps for Windows runners
    - name: Write VPN Files (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        mkdir -Force $HOME\.ssh
        $ovpnConfig = "${{ inputs.ovpn-config }}"
        $ovpnConfig | Out-File -FilePath .github\vpn.ovpn -Encoding utf8
        Get-ChildItem -Path .github\vpn.ovpn
    - name: Install openvpn community (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |  
        choco install openvpn    
    - name: VPN Connect (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        & "openvpn --connect .github\vpn.ovpn"
