name: ovpn3-connector
description: 
  Setup vpn using a self-contained .ovpn file
inputs:
  ovpn-config:
    description: Complete self-contained .ovpn file
    required: true
  vpn-user:
    description: Username for the VPN
    required: false
  vpn-pass:
    description: Password for the VPN
    required: false
runs:
  using: composite
  steps:
    - name: Write VPN Files
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ovpn-config }}" > .github/vpn.ovpn
        ls -al .github/vpn.ovpn
    - name: Install openvpn3
      shell: bash
      run: |
         apt-get update && apt-get install openvpn
    - name: VPN Connect
      shell: bash
      run: |
        sudo chown -R openvpn:openvpn /var/lib/openvpn3
        { printf "${{ inputs.vpn-user }}\n${{ inputs.vpn-pass }}\n" ; } | openvpn3 session-start --config .github/vpn.ovpn
